### ISSUE TITLE
Not working - 404

### ISSUE THREAD

**Issue by Mat001** [Aycn0/flask_loading_screen#3]
Hey

Looks like Flask starts on http://10.113.198.72:5000/, but that gives 404 not found.

**Comment by 3E5F** [comment]
Hey @Mat001, are you using Python 2 or Python 3? Also what steps can I take to replicate the issue?

EDIT: I was able to replicate the issue. Looking into it.

**Comment by Mat001** [comment]
Hey. I'm using Python 3.9.
I cloned your repo.
I pip installed Flask and ran the app: python3 app.py.
The app info shows that IP address of the service. But going to the link gives 404 error.

**Comment by Mat001** [comment]
Actually my bad. Once I specified the endpoint in the url it worked.
But I removed (0.0.0.0) from the app.run so I used port 5000. Then once the app started I went to http://127.0.0.1:5000/target_endpoint and it worked.
Maybe it works with app.run(0.0.0.0), didn't check that. But it works with removing (0.0.0.0) part.
I can see the blue loading screen with dotted spinner

**Comment by 3E5F** [comment]
Oh nice! Just confirmed that it works with 0.0.0.0 as well. Glad you got it working! Cheers!
